### ISSUE TITLE
Incrementing ids leaves HashGraph is sorry state

### ISSUE THREAD

**Issue by glennhickey** [vgteam/libbdsg#51]
If I do
```
hashgraph->increment_node_ids(k);
copy_graph(hashgraph, target);
```
I get a segfault (same code works with packed graph).  

But if I do
```
hashgraph->increment_node_ids(k);
hasgraph->reassign_node_ids([](nid_t node_id) { return node_id; });
copy_graph(hashgraph, target);
```
it's okay.  To reproduce (in vg), just comment out the `reassign_node_ids()` call in `vg concat` here: https://github.com/vgteam/vg/pull/2692/files#diff-4178eec0eda65c2fd8385e1bd8f03d57R97-R98
and run the test
```
cd test ;  prove -v t/09_vg_concat.t 
```

**Comment by jeizenga** [comment]
@adamnovak This looks like an issue with the `id_offset` member you added. I think I could get away with removing it though. What was the logic for including it?

**Comment by adamnovak** [comment]
It's there to allow O(1) ID increment. I think I wanted that for `vg ids -j`, so we wouldn't have to re-hash everything.

You could rip it out, but it should be able to work properly; it's basically just an overlay. Maybe it wants to become a real overlay?

**Comment by jeizenga** [comment]
If you want to serialize it, an overlay probably wouldn't cut it. The serialize methods typically depend on the internals of the graph, which overlays pointedly ignore. I think I'm going to rip it out since it sounds to me like we really want to replace the internals of the graph sooner or later regardless.
